name: Compiles
on: [push]
jobs:
  get_default_env:
    name: Build alturia firmware
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: [alturia_v1_2, rpi_pico]
    steps:
      - uses: actions/cache@v4
        id: zepyhr_workspace_cache
        with:
          path: ~/zephyrproject/
          key: zephyr_workspace_cache_v1

      - uses: actions/cache@v4
        id: zepyhr_sdk_cache
        with:
          path: ~/zephyr-sdk-0.16.8
          key: zephyr_sdk_cache

      - name: Install kitware archives
        run: |
          wget https://apt.kitware.com/kitware-archive.sh
          sudo bash kitware-archive.sh

      - name: Install zephyr dependencies
        run: |
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

      - name: Install west
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade west

      - name: Initialize zephyr repository
        if: steps.zepyhr_workspace_cache.outputs.cache-hit != 'true'
        run: |
          cd ~
          west init zephyrproject
          cd zephyrproject
          west update
          west zephyr-export

      - name: Initialize zephyr python dependencies
        run: |
          pip3 install -r ~/zephyrproject/zephyr/scripts/requirements.txt

      - name: Install zephyr-sdk
        if: steps.zepyhr_sdk_cache.outputs.cache-hit != 'true'
        run: |
          cd ~
          ls -lah
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          tar xvf zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          cd zephyr-sdk-0.16.8
          ./setup.sh -t arm-zephyr-eabi -h -c

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Zephyr custom branch
        run: |
          cd ~/zephyrproject/zephyr
          git checkout tags/v3.7.0
          west update

      - name: Install alturia build dependencies
        run: |
          sudo apt install uncrustify
          pip3 install sympy scipy numpy

      - name: Build alturia
        env:
          ZEPHYR_BASE: /home/runner/zephyrproject/zephyr
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
        run: |
          west build -b ${{ matrix.board }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board }}.elf
          path: build/zephyr/zephyr.elf
          if-no-files-found: error
